### ISSUE TITLE
Back button closed app

### ISSUE THREAD

**Issue by diruna** [jasonelle-archive/jasonelle-v2#13]
I'm basically want to convert part of my website to become android app. I'm using web container, but the problem is when i tried on my xiaomi note 3 the back button is closing the app instead of back to previous page.

Could someone show me what i'm doing wrong?

**Comment by clsource** [comment]
Please provide more details about your website and jason document you are using. Thank you.

**Comment by idimeca** [comment]
I was facing the same issue and solved it using this code in ViewActivity.

`public void onBackPressed() {
        if(backgroundWebview.canGoBack()) {
            backgroundWebview.goBack();
        } else {
            super.onBackPressed();
        }
    }`

Idi

**Comment by christianswanepoel** [comment]
Awesome - can confirm this fixes the issue.
https://github.com/jasonelle/jasonelle/issues/13#issuecomment-454053420

**Comment by nielsonsantana** [comment]
> I was facing the same issue and solved it using this code in ViewActivity.
> 
> `public void onBackPressed() { if(backgroundWebview.canGoBack()) { backgroundWebview.goBack(); } else { super.onBackPressed(); } }`
> 
> Idi

I tested and this code works very well.

**Comment by nielsonsantana** [comment]
I think that another improvement over @idimeca code, could be that every time application go to home page the `backgroundWebview` browsing history be cleared. It's because when you are at home page and press back, your application must close and not go to another page in the browser history. This is the behavior of native applications. 

I don't know how do it but I'm interested in try. Also, would be nice have some tips to accomplish it.

**Comment by clsource** [comment]
Yeah. Sounds like something that could be worked on. :)
