### ISSUE TITLE
New documentation doesn't present the api.

### ISSUE THREAD

**Issue by realitix** [jasonelle-archive/jasonelle-v2#69]
Hello,
In the old documentation, there was a detailed description of the API (actions for example). In the new one, I can't find API documentation.

How do you manage it?

**Comment by christianswanepoel** [comment]
The old docs still live - https://jasonelle.com/jasonette-old-docs/

**Comment by realitix** [comment]
Indeed but it's named "old doc", it means "deprecated". A newcomer will not see the old doc.

We should write a proper API documentation. We should find a good tool to generate an API documentation (json API).

**Comment by clsource** [comment]
I was thinking of separating the docs in different sites using https://docsify.js.org/ instead of the actual bookdown.

one for the api (components, params and usage examples) jasonelle.com/docs/api
one for the developer notes (detailed arquitecture and inner workings for jasonelle developers) jasonelle.com/docs/dev
one for the tutorials and additional info jasonelle.com/docs/

So it would be easier to know where to go.

**Comment by realitix** [comment]
Yes docsify seems good, I will take a look.
For the current bookdown, indeed I don't think it's the best choice because it runs under the R language which is not designed for that and not very used among the android/iphone community.
